spring.application.name=backend

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://shinkansen.proxy.rlwy.net:49865/railway?sslMode=REQUIRED
spring.datasource.username=root
spring.datasource.password=DxzzzvVgIqhhGDzDBhlDcPXhUsNvTlng

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

# ================= JWT =================
jwt.secret=b5fc1ec4cbab27aef63c60cb94a52fe8
jwt.access-expiration-ms=900000
jwt.refresh-expiration-ms=604800000

# ================= REDIS =================
spring.redis.host=localhost
spring.redis.port=6379
# spring.redis.password=${SPRING_REDIS_PASSWORD}